(MAPC 'ATTACHFEAT
'(
  ; Synonymous
  (meet meeting)
  (care treatment treatments)
  (come came)
  (pain hurt hurting)
  (medicine medicines medication medications drug drugs pill pills med meds dose)
  (drive drove driving)
  (mention say)
  (tell told say inform informed notify notified)
  (chemotherapy chemo chemotherapies)
  (know aware understand)
  (bring brings)
  (symptom symptoms)
  (lose lost losing)
  (much lot)
  (congratulations congrats congratulate commend)
  (die died dead pass passed depart perish)
  (effect effects)
  (infection infections)
  (under underneath)
  (lead leading)
  (have having)
  (trouble troubles problem problems issue issues hard difficulty)
  (concentrate concentrating focus focusing)
  (recommend recommending recommended)
  (advise advising advises advised)
  (suggest suggests suggesting suggested)
  (give gives given giving)
  (prescribe prescribes prescribed prescribed)
  (elaborate continue describe)
  (can could)
  (might could)
  (scale rate rating)
  (part parts section sections area areas)
  (take taking)
  (redness red)
  (respond responded react reacted)
  (made make)
  (okay alright well good fine)
  (wake waking)
  (day daytime)
  (happen happens)
  (thought think consider considered look looked)
  (sleep sleeping)
  (trigger triggers triggered triggering)
  (provoke provokes provoking provoked)
  (cause causing causes caused trigger provoke)
  (recently lately)
  (chance chances)
  (low small minimal)
  (recover recovery survive survival fine)
  (cure curable recover recovery solution fix miracle)
  (alone yourself)
  (dose doses dosage dosages)
  (try trying attempt attempting)
  (bad horrible terrible)
  (guess guessing)
  (depend depends conditional)
  (less lower low decrease decreased)
  (improve improving)
  (wondering asking unsure)

  ; General
  (cancer-illness cancer disease condition illness)
  (affirm pos posadv)
  (anyone-here-with-you here with alone by)
  (know-gen know sure aware understand)
  (think-gen think thoughts thought feel feelings feeling believe)
  (frequently frequent often more much)
  (sleep bed bedtime wake waking awake insomnia night nighttime)
  (family parents siblings sibling grandparents)
  (parent parents mother father mom dad)
  (child children grandchild grandchildren son daughter)
  (married marry marriage spouse partner husband wife)
  (before prior lead)
  (feeling feel doing)
  (work works working help helping treat treating effective)
  (want-gen want wanting need needing)
  (more-info learn hear tell say more additional elaborate)
  (predict tell say know)
  (number one number-plur)
  (number-plur two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen)
  (number-vague few some many several couple)
  (elapsed-time-plur years months)
  (elapsed-time year month elapsed-time-plur)
  (body-part lung lungs bone bones chest back shoulder shoulders)
  (appreciate like love enjoy)
  (avatar-items shirt sweater pants clothes clothing style glasses hat hair haircut furniture voice)

  ; Medical history
  (quit quitting stop stopping stopped forgo forgoing)
  (smoke smokes smoking smoked cigarettes cigarette tobacco)
  (drink drinking drank wine alcohol beer drunk inebriated)
  (taken-drug taken take used use smoke)
  (history background past experience)
  (medical-history history drink smoke recreational family)
  (experienced experiencing having had have suffered suffering diagnosed)
  (recreational drugs marijuana weed)

  ; Side effects
  (side-effect-addiction addiction addicted high dependent withdrawal crave craving cravings)
  (side-effect-fatigue fatigue fatigued exhaustion exhausted sleepiness sleepy sleep tiredness tired drowsy insomnia)
  (side-effect-appetite appetite eating eat hunger hungry)
  (side-effect-nausea nausea vomiting vomit sick sickness)
  (side-effect-neuropathy neuropathy numb numbness tingle tingling)
  (side-effects-insignificant side-effect-fatigue side-effect-appetite)
  (side-effects-moderate side-effect-nausea diarrhea)
  (side-effects-significant hair side-effect-neuropathy side-effect-addiction blood infection)

  ; Treatment goals
  (cancer-fight fight fighting battle battling treat treating cure curing)
  (cancer-live live living survive surviving cure curing remission)
  (cancer-goals goal goals objective objectives priority priorities value values valuing)

  ; Chemotherapy
  (chemotherapy-injection injection injections vein veins needle needles)
  (chemotherapy-IV IV tube tubes)
  (mediport infusaport port)
  (chemotherapy-consult consult consulting ask asking discuss discussing talk talking)
  
  ; Diagnosis details
  (symptom-weight weight skinny skinnier heavy heavier fat)
  (symptom-appetite appetite eating)
  (diagnosis-symptom symptom symptoms weight skinny skinnier appetite eating constipation constipated)
  (diagnosis-non-symptom headache headaches chill chills fever fevers nausea eyesight eyes)
  (diagnosis-tests diagnosis test tests result results)

  ; Mental health
  (ment-health mental depression depressed anxiety anxious worry worried worrying anxiousness unease uneasy schizophrenia)
  (energy mood concentrate ment-health med-ment-health health illness)
  (antidepressant SSRI Prozac fluoxetine sertraline Zoloft Celexa citalopram Lexapro escitalopram paroxetine Paxil Pexeva)
  (therapy therapist counseling counselor)
  (ment-treatment antidepressant therapy)

  ; Medicine
  (medicine-gen medicine medicine-particular)
  (medicine-particular pain-med pain-med-other blood-pressure-med med-narcotic)
  (medicine-taking medicine pain-med)
  (medicine-not-taking pain-med-other med-narcotic)
  (pain-med lortab vicodin norco)
  (pain-med-other ibuprofen aleve)
  (med-narcotic narcotic narcotics oxycodone morphine)
  (med-chemotherapy carboplatin gemcitabine denosumab zometa)
  (med-ment-health antidepressant SSRI Prozac fluoxetine sertraline Zoloft Celexa citalopram Lexapro escitalopram paroxetine Paxil Pexeva)
  (blood-pressure-med cozar)
  (sleep-medication ambien nyquil lunesta)
  (med-give recommend advise suggest give prescribe)
  (med-take take taking get getting use using on prescribed)
  (med-past took taken used gotten prescribed)
  (med-time every time times hour hours minute minutes day days week weeks)
  (med-time-gen while period med-time)
  (med-better better stronger effective heavier)
  (med-for for work)
  (med-help care help helping helpful better effective work working)
  (med-notice notice tell detect feel)
  (med-wait wait give try use)
  (med-increase maximize maximizing increase increasing upping)
  (med-dosage much many milligrams grams)

  ; Pain
  (pain-bad bad much strongly intensely badly)
  (pain-return come back return)

  ; Radiation
  (radiation-help help better alleviate reduce comfort comfortable)

  ; Comfort care
  (comfort-care-word comfort palliative hospice care)
  (palliative comfort)

  ; Prognosis
  (spread spreading metastasized metastatic)
  (cancer-increase increase spread)
  (prog-future will going)

  ; Sleep
  (sleep-prob problem insomnia)
  (sleep-thought thought thoughts head mind brain)
  (sleep-awake awake up)

  ; Telling family
  (family-pron family they)

))