(MAPC 'ATTACHFEAT
'(
  ; Synonymous
  (go going gone went)
  (meet meeting)
  (care treatment treatments)
  (call refer)
  (alright okay ok fine)
  (come came)
  (close closest) 
  (pain hurt hurting)
  (answer answered answering say)
  (medicine medicines medication medications drug drugs pill pills med meds dose)
  (drive drove driving)
  (appointment meeting consultation session)
  (someone person friend anyone anybody somebody)
  (mention say)
  (talk talks talked talking)
  (speak spoke speaking speaks)
  (share sharing tell telling confide confiding)
  (tell told say inform informed review reviewed notify notified convey conveying telling saying informing notifying discuss share)
  (chemotherapy chemo chemotherapies)
  (know aware understand familiar informed acquainted)
  (bring brings)
  (symptom symptoms)
  (lose lost losing)
  (much lot lots many)
  (congratulations congrats congratulate commend)
  (die died dying dead pass passed depart perish)
  (effect effects)
  (response respond responded responds responding responses effect)
  (infection infections)
  (under underneath)
  (lead leading)
  (have having has had)
  (difficult hard impossible tough challenging)
  (trouble troubles problem problems issue issues hard difficulty)
  (concentrate concentrating focus focusing)
  (recommend recommending recommended)
  (advise advising advises advised)
  (suggest suggests suggesting suggested)
  (give gives given giving gave)
  (provide offer give supply)
  (prescribe prescribes prescribed prescribed)
  (elaborate continue describe expand)
  (can could)
  (might can may)
  (maybe possible plausible conceivable perhaps conceivably possibly)
  (scale rate rating)
  (part parts section sections area areas)
  (take taking)
  (redness red)
  (respond responded react reacted)
  (made make makes making)
  (create created creating made produce produced producing)
  (okay alright well good fine)
  (wake waking)
  (day daytime)
  (happen happens happened happening occur occurs occurring occurred appear appears appearing appeared)
  (look looking looked)
  (thought think thinking consider considered considering look)
  (sleep sleeping)
  (trigger triggers triggered triggering)
  (provoke provokes provoking provoked)
  (cause causing caused trigger triggered triggering provoke provoked provoking produce produced producing result resulted resulting)
  (reason cause source origin root)
  (make-change-words cause create)
  (recently recent lately)
  (chance chances)
  (low small minimal)
  (recover recovery survive survival fine)
  (cure cured curable recover recovery solution fix miracle)
  (alone yourself)
  (long longer further)
  (dose doses dosage dosages)
  (try trying attempt attempting)
  (bad horrible terrible awful negative dreadful unpleasant)
  (frightening scary worrisome upsetting distressing troubling concerning daunting alarming disturbing)
  (frightened afraid worried upset anxious scared nervous apprehensive distressed troubled uneasy concerned)
  (frightens scares worries upsets distresses troubles concerns alarms bothers)
  (frighten scare worry upset distress trouble concern alarm bother)
  (fear-pl fears worries anxieties misgivings doubts)
  (fear-sing fear worry anxiety misgiving doubt)
  (fear-words fear-pl fear-sing)
  (anxiety-word frightening frightened frightens fear-words)
  (guess guessing guesses guessed)
  (depend depends conditional)
  (less lower low decrease decreased)
  (improve improving)
  (make-better better help helped improve improved boost boosted)
  (odds chance prospects likelihood probability possibility potential)
  (wondering asking unsure)
  (option options)
  (conversation discussion)
  (sound sounds sounded sounding seem seems seemed seeming appear appears appeared appearing)
  (coffee caffeine)
  (anything something)
  (like same similar identical comparable as)
  (seems looks)
  (similarity likeness commonality resemblance correspondance)
  (now present today)
  (hopeful-words hope hopeful confident optimistic believe upbeat)
  (happy-words happy pleased delighted glad)
  (positive-words hopeful-words happy-words good)
  (spend spending devote devoting)
  (honest truthful forthcoming forthright frank open candid direct straight straightforward upfront)
  (honest-adv honestly truthfully frankly openly candidly directly)
  (available present there around attendence)
  (reassure comfort soothe)
  (fact facts truth)
  (everything all full whole entire)
  (succumb die victim)
  (stop stopped prevent prevented keep kept)
  (change changed changing changes alter alters altering altered transform transforms transforming transformed)
  (difference change increase decrease)
  (seem seemed seeming appear appeared appearing look)
  (in into)
  (sick ill unwell)
  (cell cells tissue tissues)
  (lung lungs)
  (body organ organs lung cell)
  (complicated complex convoluted)
  (obvious clear simple easy evident)
  (stage stages)
  (final last terminal)
  (assume presume accept act)
  (be been is are were)
  (explain explained explaining explained clarify clarified clarifies clarifying describe describes described describing)
  (summarize explain)
  (summary explanation)
  (despite regardless although though)
  (confused lost bewildered)
  (discuss discussing talk talking discussed talked)
  (anticipate anticipated anticipating expect expecting expected look forsee forecast count bank predict predicting predicted)
  (ready interested prepared willing)
  (interest interested interesting interests)
  (certain definite sure)
  (process processes processed processing)
  (imagine imagined imagines imagining)
  (startle startled startling startles)
  (surprise surprised surprising surprises)
  (alarm alarming alarmed alarms)
  (startle-words startle surprise alarm jarring)
  (resilience backbone spirit strength strong resilient bravery brave courage courageous)
  (ahold hold)
  (help helped helping helps assist assists assisting assisted support supported supporting supports aid aiding aided aids)
  (thankful grateful)


  
  ; ASR errors
  (TALKING talkin)
  (ASKING askin)
  (YA yes)
  (DATING taking)
  ; General
  (cancer-illness cancer disease condition illness prognosis tumor)
  (posadv-affirm certainly course absolutely sure definitely)
  (affirm pos posadv)
  (anyone-here-with-you here with alone by)
  (know-gen know knew knowing sure aware understand understood understanding)
  (learn-gen learn learned learning discover discovered discovering see saw seeing know-gen)
  (information-gen information info detail details knowledge depth)
  (think-gen think thinking thoughts thought feel feelings feeling believe find)
  (understanding-gen following comprehending understanding)
  (understand-gen know-gen think-gen follow comprehend understanding-gen)
  (opinion-gen opinions thought thoughts value values need needs preference preferences)
  (frequently frequent often much)
  (sleep bed bedtime wake waking awake insomnia night nighttime)
  (family parents siblings sibling grandparents relative)
  (parent parents mother father mom dad)
  (child children grandchild grandson grandchildren son daughter)
  (married marry marriage spouse partner husband wife)
  (before prior lead)
  (feeling feel feels felt doing)
  (work worked works working help helping treat treated treating effective successful efficacious helpful)
  (want-gen want wanting need needs needing desire desiring hope hoping hoped like)
  (plan-gen thought plan planned planning intend intended intending aim aiming aimed want-gen)
  (learn learned learning learns)
  (hear heard hearing hears)
  (more-info learn hear tell told say said more additional elaborate)
  (predict tell say know)
  (number-total one number-plur)
  (number-plur two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen)
  (number-vague few some many several couple)
  (elapsed-time-plur years months)
  (elapsed-time year month elapsed-time-plur)
  (time-words time elapsed-time)
  (body-part lung lungs bone bones chest back shoulder shoulders)
  (appreciate like love enjoy)
  (avatar-items shirt sweater pants clothes clothing style glasses hat hair haircut furniture voice)
  (tag-question right correct accurate)
  (question questions)
  (question-word question inquiry inquiries query queries concerns concern)
  (ask-gen ask asking talk talking)
  (incorrect wrong mistaken)
  (unusual rare infrequent atypical unlikely impossible special odd abnormal peculiar irregular)
  (usual likely common probable typical normal regular usually commonly typically normally regularly)
  (seldom rarely never infrequently)
  (exception anamoly outlier oddity deviation abnormality peculiarity irregularity)
  (left remaining)
  (become becomes became becoming get gets getting got gotten)
  (move moved moving go gone)
  (grow grows growing grown grew)
  (shrink shrinking shrank shrunk decrease)
  (specific precise exact detailed)
  (prediction predictions guess conjecture conjectures projection projections)
  (allow let permit)
  (important valuable precious dear)
  (normal natural understandable)
  (emotion emotions reaction reactions feeling)
  (contact call notify phone speak talk)

  ; Medical history
  (QUIT quitting STOP stopping stopped forgo forgoing)
  (SMOKE smokes smoking smoked cigarettes cigarette tobacco)
  (SMOKE-WORDS QUIT SMOKE)
  (DRINK drinking drank wine alcohol beer drunk inebriated)
  (TAKEN-DRUG taken TAKE used use SMOKE)
  (HISTORY background PAST experience)
  (MEDICAL-HISTORY HISTORY DRINK SMOKE RECREATIONAL FAMILY)
  (EXPERIENCED experiencing having had HAVE suffered suffering diagnosed)
  (RECREATIONAL DRUGS marijuana weed)
  ; Side effects
  (SIDE-EFFECT-ADDICTION addiction addicted high dependent withdrawal crave craving cravings)
  (SIDE-EFFECT-FATIGUE fatigue fatigued exhaustion exhausted sleepiness sleepy SLEEP tiredness TIRED drowsy insomnia)
  (SIDE-EFFECT-APPETITE appetite eating eat hunger hungry)
  (SIDE-EFFECT-NAUSEA nausea vomiting vomit SICK SICKNESS)
  (SIDE-EFFECT-NEUROPATHY neuropathy numb numbness tingle tingling)
  (SIDE-EFFECTS-INSIGNIFICANT SIDE-EFFECT-FATIGUE SIDE-EFFECT-APPETITE)
  (SIDE-EFFECTS-MODERATE SIDE-EFFECT-NAUSEA diarrhea)
  (SIDE-EFFECTS-SIGNIFICANT hair SIDE-EFFECT-NEUROPATHY SIDE-EFFECT-ADDICTION blood INFECTION)
  ; Treatment goals
  (cancer-fight fight fighting battle battling treat treating cure curing)
  (cancer-live live living survive surviving cure curing remission)
  (cancer-goals goal goals objective objectives priority priorities prioritize preference preferences value values valuing)
  (treatment-option option options possibility possibilities treatments treatment care choice choices decision decisions)
  (prognosis-notification-words see saw seen give shown show present presented supply supplied inform informed)

  ; Chemotherapy
  (CHEMOTHERAPY-INJECTION injection injections vein veins needle needles)
  (CHEMOTHERAPY-IV iv tube tubes)
  (MEDIPORT infusaport port)
  (CHEMOTHERAPY-CONSULT consult consulting ask ASKING discuss discussing talk TALKING)
  ; Diagnosis details
  (symptom-weight weight skinny skinnier heavy heavier fat)
  (symptom-appetite appetite eating)
  (diagnosis-symptom symptom symptoms weight skinny skinnier appetite eating constipation constipated)
  (diagnosis-non-symptom headache headaches chill chills fever fevers nausea eyesight eyes)
  (diagnosis-tests diagnosis test tests result results study studies scan scans)
  (diagnosis-more more other another further additional)

  ; Mental health
  (MENT-HEALTH mental depression depressed anxiety anxious worry worried worrying anxiousness unease uneasy schizophrenia down)
  (ENERGY mood CONCENTRATE MENT-HEALTH MED-MENT-HEALTH health illness)
  (ANTIDEPRESSANT ssri prozac fluoxetine sertraline zoloft celexa citalopram lexapro escitalopram paroxetine paxil pexeva)
  (THERAPY therapist counseling counselor)
  (MENT-TREATMENT ANTIDEPRESSANT THERAPY)
  ; Medicine
  (MEDICINE-GEN MEDICINE MEDICINE-PARTICULAR)
  (MEDICINE-PARTICULAR PAIN-MED PAIN-MED-OTHER BLOOD-PRESSURE-MED MED-NARCOTIC)
  (MEDICINE-TAKING MEDICINE PAIN-MED)
  (MEDICINE-NOT-TAKING PAIN-MED-OTHER MED-NARCOTIC)
  (PAIN-MED lortab vicodin norco)
  (PAIN-MED-OTHER ibuprofen aleve)
  (MED-NARCOTIC narcotic narcotics oxycodone morphine)
  (MED-CHEMOTHERAPY carboplatin gemcitabine denosumab zometa)
  (MED-MENT-HEALTH ANTIDEPRESSANT ssri prozac fluoxetine sertraline zoloft celexa citalopram lexapro escitalopram paroxetine paxil pexeva)
  (BLOOD-PRESSURE-MED cozar)
  (SLEEP-MEDICATION ambien nyquil lunesta)
  (MED-GIVE RECOMMEND ADVISE SUGGEST GIVE PRESCRIBE)
  (MED-TAKE TAKE taking get getting use using on prescribed)
  (MED-PAST took taken used gotten prescribed)
  (MED-TIME every time times hour hours minute minutes DAY days week weeks)
  (MED-TIME-GEN while period MED-TIME)
  (MED-BETTER better stronger effective heavier)
  (MED-FOR for WORK)
  (MED-HELP CARE HELP helping HELPFUL better effective WORK working benefit)
  (MED-NOTICE notice TELL detect feel observe)
  (MED-WAIT wait GIVE TRY use)
  (MED-INCREASE maximize maximizing increase increasing upping)
  (MED-DOSAGE MUCH many milligrams grams)
  ; Pain
  (pain-bad bad much strongly intensely badly)
  (pain-return come back return)
  (painful unpleasant distressing)
  (pain unpleasantness suffering agony affliction discomfort hurt)
  (make-worse worse worsen harm hurt)
  (pain-alleviate treat manage control alleviate reduce ease relieve lessen diminish allay assuage palliate moderate mollify improve relieving improving lessening palliating alleviating controlling managing)

  ; Radiation
  (radiation-help help work better alleviate reduce comfort comfortable decrease decreasing)
  (radiation-treatment radiation care therapy therapies treatment treatments)

  ; Comfort care
  (comfort-care-word comfort comfortable palliative hospice palliation)
  (palliative comfort)
  (referral request petition)
  (nurse nurses nursing)
  (company companies service services business businesses agency agencies)
  (home homes)
  (visit meet)

  ; Prognosis
  (spread spreading metastasized metastatic)
  (cancer-increase increase spread spreading grow grown growing advance advancing advanced progress progressing progressed develop developing developed)
  (prog-future will going)
  (good positive fine great)
  (predictor indicator sign signal indication pointer hint)
  (second other another different)
  (idea thought)
  (beneficial helpful useful worth great good best worthwhile better)
  (should must ought)
  (stage-four four fourth final)

  ; Prognosis Understanding
  (TREATMENT treatments DRUGS drug THERAPY therapies trials trial studies study)
  (EXPERIMENTAL clinical new)
  (HEALTHY health fit shape condition strong GOOD)
  (NOW today SECOND moment present)
  (PAST HISTORY last former previous previously former)
  (UNCLE fred relative people patients he him)
  (PROGNOSIS-MORE LONG more further)
  ; Prognosis Bargaining
  (PERSON-PL people patients cases)
  (MOST majority all preponderance everyone)
  (FEW little couple)
  (GRAD-WORDS grandson graduation graduate)
  ; Sleep
  (SLEEP-PROB problem insomnia)
  (SLEEP-THOUGHT THOUGHT thoughts head mind brain)
  (SLEEP-AWAKE awake up)
  ; Telling family
  (family-pron family child they them)
  (love care appreciate)
  (gentle kind considerate understanding supportive)
  (doctor-pron I we me us)
  (brace braced bracing)
  (worst inevitable)
  (position place shoes)
  (perspective view viewpoint outlook point)

  ; Reason for Cancer
  (result consequence effect repercussion ramification culmination aftermath product effect affect)
  (because since)
  (destroy destroys destroyed destroying wreck wrecks wrecked wrecking ruin ruins ruining ruined)
  (impair impairs impaired impairing damage damages damaging damaged)
  (debilitate debilitating debilitated debilitates harm harms harming harmed hurt hurts hurting weaken weakens weakened weakening)
  (hurt-words destroy impair debilitate)
  (tumor mass cyst malignancy carcinoma growth neoplasm)
  (sudden suddenly unexpected unexpectedly rapid rapidly abrupt abruptly quickly quick)
  (life living world lifestyle situation)

))