;; (how did you like the weather in your hometown ?)
;;	(hometown-weather)
;;		from-hometown-weather-input
;;			(0 the weather in my hometown 0)
;;			gist-question:(3 how 2 like the weather 2 hometown 0)

(MAPC 'ATTACHFEAT
'(
  (snow snowy snowing snows blizzard ice)
  (sun sunny)
  (rain rainy)
	(cold colder freezing frigid icy)
	(moderate pleasant mild)
	(have had has)
  (lot lots)
	(season-names fall spring summer winter)
	(like liked loved love)
))
  

(READRULES '*hometown-weather-input*
'( 
  1 (0 four seasons 0) 
    2 ((The weather in your hometown has all four seasons \.)  (Hometown-weather)) (0 :gist) 		
  1 (0 hot 0)
    2 (0 hot 2 summer 0)
      3 ((The weather in your hometown is hot during summer \.) (Hometown-weather)) (0 :gist)
    2 (0 summer 2 hot 0)
      3 ((The weather in your hometown is hot during summer \.) (Hometown-weather)) (0 :gist)
    2 (0 NEG 1 like 1 hot 0) 
      3 ((You do not like the weather to be hot \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 not 1 hot 0)
      3 ((The weather in your hometown is not too hot \.)  (Hometown-weather)) (0 :gist) 		
    2 ((Probably the weather in your hometown is hot \.)  (Hometown-weather)) (0 :gist) 		
  
  1 (0 snow 0)
    2 (0 snow 2 winter 0)
      3 ((The weather in your hometown is snowy during winter \.) (Hometown-weather)) (0 :gist)
    2 (0 winter 5 snow 0)
      3 ((The weather in your hometown is snowy during winter \.) (Hometown-weather)) (0 :gist)
    2 (0 NEG 1 like 2 snow 0) 
      3 ((You do not like the weather in your hometowen to be snowy \.)  (Hometown-weather)) (0 :gist) 		
    2 ((Probably the weather in your hometown is snowy \.)  (Hometown-weather)) (0 :gist) 		       
  1 (0 rain 0)
    2 (0 rain 2 season-names 0)
      3 ((The weather in your hometown is rainy during 4 \.) (Hometown-weather)) (0 :gist)
    2 (0 season-names 2 rain 0)
      3 ((The weather in your hometown is rainy during 2 \.) (Hometown-weather)) (0 :gist)
    2 (0 we have 2 lot 1 rain 0) 
      3 ((The weather in your hometown is rainy \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 it be 1 rain 0) 
      3 ((The weather in your hometown is rainy \.)  (Hometown-weather)) (0 :gist) 		
    2 ((Probably the weather in your hometown is rainy \.)  (Hometown-weather)) (0 :gist) 		
  
  1 (0 cold 0)
    2 (0 cold 2 winter 0)
      3 ((The weather in your hometown is cold during winter \.) (Hometown-weather)) (0 :gist)
    2 (0 winter 3 cold 0)
      3 ((The weather in your hometown is cold during winter \.) (Hometown-weather)) (0 :gist)
    2 (0 we have 2 lot 1 cold 0) 
      3 ((The weather in your hometown is cold \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 it got 1 cold 0) 
      3 ((The weather in your hometown is cold \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 it be 1 cold 0) 
      3 ((The weather in your hometown is cold \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 weather be 1 cold 0) 
      3 ((The weather in your hometown is cold \.)  (Hometown-weather)) (0 :gist) 		
    2 ((Probably the weather in your hometown is cold \.)  (Hometown-weather)) (0 :gist) 		
  
  1 (0 moderate 0)
    2 (0 moderate 2 season-names 0) 
      3 ((The weather in your hometown is moderate \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 season-names 2  moderate 0) 
      3 ((The weather in your hometown is moderate \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 season-names it is 4 moderate 0) 
      3 ((The weather in your hometown is moderate \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 we have 3 moderate 0) 
      3 ((The weather in your hometown is moderate \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 it be 3 moderate 0) 
      3 ((The weather in your hometown is moderate \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 it is got 3 moderate 0) 
      3 ((The weather in your hometown is moderate \.)  (Hometown-weather)) (0 :gist) 		
    2 ((Probably the weather in your hometown is moderate \.)  (Hometown-weather)) (0 :gist) 		
    
  1 (0 warm 0)
    2 (0 warm 2 season-names 0) 
      3 ((The weather in your hometown is warm \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 season-names 2  warm 0) 
      3 ((The weather in your hometown is warm \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 season-names it is 4 warm 0) 
      3 ((The weather in your hometown is warm \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 we have 3 warm 0) 
      3 ((The weather in your hometown is warm \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 it be 3 warm 0) 
      3 ((The weather in your hometown is warm \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 it is got 3 warm 0) 
      3 ((The weather in your hometown is warm \.)  (Hometown-weather)) (0 :gist) 		
    2 ((Probably the weather in your hometown is warm \.)  (Hometown-weather)) (0 :gist) 		


      
  1 (0 I like 2 seasons 0) 
    2 ((You like the weather in your hometown to have all the seasons \.)  (Hometown-weather)) (0 :gist) 		
  1 (0 I like 2 change 2 seasons 0) 
    2 ((You like the weather in your hometown to have all the seasons \.)  (Hometown-weather)) (0 :gist) 		
  1 (0 sun 0)
    2 (0 I like 2 sun 0) 
      3 ((You like the weather in your hometown to be sunny \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 NEG enough 1 sun 0)
      3 ((The weather in your hometown is not enough sunny \.) (Hometown-weather)) (0 :gist)
    2 ((Probably the weather in your hometown is sunny \.)  (Hometown-weather)) (0 :gist) 		
  
  1 (0 same as rochester  0) 
    2 ((The weather in your hometown is same as rochester \.)  (Hometown-weather)) (0 :gist) 		
  1 (0 same as here 3  0) 
    2 ((The weather in your hometown is same as rochester \.)  (Hometown-weather)) (0 :gist) 		 
  1 (0 season-names 0) 
    2 (0 I like 2 season-names 0) 
      3 ((You like that the weather in your hometown has all the seasons \.)  (Hometown-weather)) (0 :gist) 		
    2 (0 season-names 0) 
      3 ((You talked about how seasons and the weather in your hometown is \.)  (Hometown-weather)) (0 :gist) 		
  1 (0 NEG 1 like 2 weather 0) 
    2 ((You do not like the weather in your hometown \.)  (Hometown-weather)) (0 :gist) 		
    
  1 (0)
      2 ((NIL gist \: Nothing found for how the weather in your hometown is \.) (Hometown-weather)) (0 :gist)

))
   

(READRULES '*reaction-to-hometown-weather-input*
'(
  1 (0 neg like 0 hot 0)
    2 (If you are not a fan of hot weather\, then you must like rochester\!) (100 :out)
  1 (0 hot 0)
    2 (I lived in texas for a long time\, so me know hot weather very well\. Rochester is a big change for me \.) (100 :out)
  1 (0 neg like 0 snowy 0)
    2 (If you do not like snow\, then it should be hard for you in rochester\!) (100 :out)
  1 (0 snowy 0)
    2 (Oh\, I love snow\. That\'s really fun\. ) (100 :out)
  1 (0 rainy 0)
    2 (I love rain\, especially the weather after a heavy rain\.) (100 :out)
  1 (0 cold 0)
    2 (Oh\, in my opinion cold weather is better than hot\. Just be sure to stay warm when you are there\!) (100 :out)
  1 (0 moderate 0)
    2 (That\'s nice\. I love when it is around seventy five outside with a nice sunny weather\. Though it does happen only during summer in rochester \.) (100 :out)
  1 (0 warm 0)
    2 (That\'s nice\. I love when it is around seventy five outside with a nice sunny weather\. Though it does happen only during summer in rochester \.) (100 :out)
  1 (0 sun 0)
    2 (0 not enough sun 0)
      3 (I would not like hot weather but sometime\, I really miss sun here in rochester \.) (100 :out)
    2 (I would also like sunny weather\. However\, I could not stand when it is too hot \.) (100 :out)
  1 (0 same as rochester 0)
    2 (So you must be used to this kind of weather\.) (100 :out)
  1 (0 all the seasons 0)
    2 (That\'s really great to experience all seasons\.) (100 :out)
  1 (0 not like the weather 0)
    2 (Oh\, I am sorry if you don\'t like that weather\. I believe you can always find something to enjoy in any weather\.) (100 :out)  
    
  1 (0 NIL gist 0)
    2 (I find the weather to be a pretty important factor of where I want to live\.) (100 :out)
))
