;;	(Do you use facebook or skype ?)
;;	(use-facebook)
;;		from-use-facebook-input
;;			(0 I do not use social-networks 0) (0 I use social-networks 0)
;;			gist-question: (3 do you 1 facebook 0)

(MAPC 'ATTACHFEAT
'(
   (yes yeah)
   (social-networks facebook skype facetime)
   (social-networks-relevant account profile page skyping other-communication)
   (other-communication email mail mailing text phone)
   (skype skyping skyped)
   (email emailing)
   (text texting)
   (phone call telephone)
   (use used)
))


(READRULES '*use-facebook-input*
'(
   ; Reciprocal questions
   1 (0 what 2 you 0 ?)
      2 (Do I use facebook or skype ?) (0 :gist)
   1 (0 how 2 you 0 ?)
      2 (Do I use facebook or skype ?) (0 :gist)
   1 (0 do you 2 facebook 0 ?)
      2 (Do I use facebook or skype ?) (0 :gist)
   
   ; Specific answers
   1 (0 I do social-networks 0)
      2 ((You use 4 \.) (Use-facebook)) (0 :gist)
   1 (0 I also 1 social-networks 0)
      2 ((You use 5 \.) (Use-facebook)) (0 :gist)
   1 (2 yes 3 social-networks 0)
      2 ((You use 4 \.)  (Use-facebook)) (0 :gist)
   1 (1 definitely 0)
      2 ((You use social-networks \.)  (Use-facebook)) (0 :gist)
   1 (3 NEG 1 use 0) 
      2 ((You do not use social-networks \.)  (Use-facebook)) (0 :gist)
   1 (1 Not really 0) 
      2 ((You do not use social-networks \.)  (Use-facebook)) (0 :gist)
   1 (0 NEG 3 fan of 0) 
      2 ((You do not use social-networks \.)  (Use-facebook)) (0 :gist)
   1 (1 I do not 1 social-networks 0)
      2 ((You do not use 6 \.)  (Use-facebook)) (0 :gist)
   1 (0 I do 1 social-networks 0)
      2 ((You use 5 \.)  (Use-facebook)) (0 :gist)
   1 (0 I do have 1 social-networks 0)   ;; here : I do have a facebook account
      2 ((You use 6 \.)  (Use-facebook)) (0 :gist)
   1 (0 I social-networks 0)  ;; here: I skype quite a bit with the three year old
      2 ((You use 3 \.)  (Use-facebook)) (0 :gist)
   1 (0 I have 1 social-networks 0)
      2 ((You use 5 \.)  (Use-facebook)) (0 :gist)
   1 (0 I use 2 social-networks 0)
      2 ((You use 5 \.)  (Use-facebook)) (0 :gist)
   1 (0 I am on 1 social-networks 0)
      2 ((You use 6 \.)  (Use-facebook)) (0 :gist)
   1 (1 I 1 have 1 social-networks-relevant 0)
      2 ((You use social-networks \.)  (Use-facebook)) (0 :gist)
   1 (1 I 1 use 1 social-networks-relevant 0)
      2 ((You use social-networks \.)  (Use-facebook)) (0 :gist)
   1 (1 I 1 send 1 social-networks-relevant 0)
      2 ((You use social-networks \.)  (Use-facebook)) (0 :gist)
   1 (1 I social-networks-relevant 0)
      2 ((You use social-networks \.)  (Use-facebook)) (0 :gist)
   1 (0 I do not 1 post 0)
      2 ((You do not post on facebook \.) (Use-facebook)) (0 :gist)
   1 (I do not 0)
      2 ((You do not use social-networks \.) (Use-facebook)) (0 :gist) 
   1 (No 0)
      2 ((You do not use social-networks \.) (Use-facebook)) (0 :gist)   
   1 (yes 0)
      2 ((You use social-networks \.) (Use-facebook)) (0 :gist) 

   ; Unbidden answers
   1 (0 I do 1 other-communication 0)
      2 ((You use 5 \.)  (Use-facebook)) (0 :gist)
   1 (0 I do have 1 other-communication 0)
      2 ((You use 6 \.)  (Use-facebook)) (0 :gist)
   1 (0 I other-communication 0)
      2 ((You use 3 \.)  (Use-facebook)) (0 :gist)
   1 (0 I have 1 other-communication 0)
      2 ((You use 5 \.)  (Use-facebook)) (0 :gist)
   1 (0 I use 2 other-communication 0)
      2 ((You use 5 \.)  (Use-facebook)) (0 :gist)
   1 (0 I do not 1 post 0)
      2 ((You do not post on facebook \.) (Use-facebook)) (0 :gist)

   1 (0)
      2 ((NIL gist \: Nothing found for if you use social-networks \.) (Use-facebook)) (0 :gist)
))


(READRULES '*reaction-to-use-facebook-input*
'(
   1 (0 neg 1 use social-networks 0)
      2 (0 facebook 0)
         3 (I never made a facebook account\, none of my friends are on it\.) (100 :out)     
      2 (0 skype 0)
         3 (My daughter set up skype on my phone last year\. It is a great way to communicate\. Now\, I get to see her while I am talking to her\.) (100 :out)
      2 (0 facetime 0)
         3 (I haven't used facetime that much\. I prefer to just call people\.) (100 :out)
   1 (0 you use social-networks 0)
      2 (0 facebook 0)
         3 (I don\'t have a facebook account\, but it might be a good idea to make one\, to keep in touch with friends\.) (100 :out)
      2 (0 skype 0)
         3 (My daughter set up skype on my phone last year\. It is a great way to communicate\. Now\, I get to see her while I am talking to her\.) (100 :out)
      2 (0 facetime 0)
         3 (I haven't used facetime that much\. I prefer to just call people\.) (100 :out)
   1 (0 you use social-networks-relevant 0)
      2 (0 other-communication 0)
         3 (0 email 0)
            4 (I used to use my email much more before\. I find it hard to type recently\.) (100 :out)
         3 (0 text 0)
            4 (Texting is hard for me \. It takes too much\. I prefer just to call people\.) (100 :out)
         3 (0 phone 0)
            4 (I still like to call people although my daughters prefer skype \.) (100 :out)
      2 (0)
         3 (That\'s nice\. I have a facebook account\, it makes it easier to communicate with friends\.) (100 :out)
      
   1 (0 NIL gist 0)
      2 (I don\'t have a facebook account\, but it might be a good idea to make one to stay in touch with friends\.) (100 :out)
))
