(defun set-api (api) nil)
(defun set-model (model-name) nil)
(defun set-cross-encoder (cross-encoder-name) nil)
(defun init (&key use-cross-encoder api-key) nil)
(defun embed-documents (documents &key filename append api-key indices) nil)
(defun retrieve (text &key (n 5) documents+embeddings documents filename api-key indices) nil)
(defun rerank (text documents &key (n 1)) nil)
(defun retrieve+rerank (text &key (n-candidate 5) (n-result 1) documents+embeddings documents filename) nil)