;; (do you like to read ?)
;;	(like-to-read)
;;		from-like-to-read-input
;;			(0 I do not like reading 0) (0 I like reading 0)
;;			gist-question:(3 do 1 like to read 0)

(MAPC 'ATTACHFEAT
'(
  (yes yeah)
  (book-genre novel novels magazines magazine health 
	mystery mysteries fictions fiction non-fictions non-fiction romance historical detective
	humor biographies autobiography art Literature Philosophy Religion Ethics
	newspaper horror horrors satire diaries cookbooks cookbook poetry)
  (read reading reader)	
))


(READRULES '*like-to-read-input*
'(
  ; Reciprocal question
  1 (0 what 2 you 0 ?)
    2 (Do I like to read ?) (0 :gist)
  1 (0 how 2 you 0 ?)
    2 (Do I like to read ?) (0 :gist)
  1 (0 do you 2 like 2 read 0 ?)
    2 (Do I like to read ?) (0 :gist)
  1 (0 do you 2 read 0 ?)
    2 (Do I read ?) (0 :gist)

  ; Specific input
  1 (0 book-genre 0)
    2 (0 science fiction 0)
      3 ((You like reading science fiction \.)  (Like-to-read)) (0 :gist)
    2 ((You like reading 2 \.)  (Like-to-read)) (0 :gist)
  1 (0 book club 0) 
    2 ((You like reading in book club \.)  (Like-to-read)) (0 :gist) 		
  1 (0 library 0) 
    2 ((You like reading in library \.)  (Like-to-read)) (0 :gist) 		
  1 (0 kindle 0) 
    2 ((You like reading on kindle \.)  (Like-to-read)) (0 :gist) 		
  1 (0 hate 2 read 0) 
    2 ((You do not like reading \.)  (Like-to-read)) (0 :gist) 		
  1 (0 cannot 2 read 0) 
    2 ((You do not like reading \.)  (Like-to-read)) (0 :gist) 		
  1 (0 NEG 4 read 0) 
    2 ((You do not like reading \.)  (Like-to-read)) (0 :gist) 		
  1 (0 NEG 3 reader 0) 
    2 ((You do not like reading \.)  (Like-to-read)) (0 :gist) 		
  1 (1 I do not 0)
    2 ((You do not like reading \.)  (Like-to-read)) (0 :gist) 		
  1 (No 0)
    2 ((You do not like reading \.)  (Like-to-read)) (0 :gist) 		
  1 (2 yes 0) 
    2 ((You like reading \.)  (Like-to-read)) (0 :gist)	
  1 (0 like to read 0) 
    2 ((You like reading \.)  (Like-to-read)) (0 :gist) 		
  1 (0 I 3 reader 0) 
    2 ((You like reading \.)  (Like-to-read)) (0 :gist) 		
  1 (0 listen 3 book 0) 
    2 ((You like reading and listening to audio books \.)  (Like-to-read)) (0 :gist) 	

  ; Unbidden input
  1 (0 book-genre 0)
    2 (0 science fiction 0)
      3 ((You like reading science fiction \.)  (Things-like-to-read)) (0 :gist)
    2 ((You like reading 2 \.)  (Things-like-to-read)) (0 :gist)
  1 (0 hate 2 read 0) 
    2 ((No book type you like to read \.)  (Things-like-to-read)) (0 :gist)
  1 (0 cannot 2 read 0) 
    2 ((No book type you like to read \.)  (Things-like-to-read)) (0 :gist)
  1 (0 NEG 2 read 0)
    2 ((No book type you like to read \.)  (Things-like-to-read)) (0 :gist)
  1 (1 I do not 0)
    2 ((No book type you like to read \.)  (Things-like-to-read)) (0 :gist)
  1 (No 0)
    2 ((No book type you like to read \.)  (Things-like-to-read)) (0 :gist)	

  1 (0)
    2 ((NIL gist \: Nothing found for whether you like reading \.)  (Like-to-read)) (0 :gist)
))


(READRULES '*reaction-to-like-to-read-input*
'(
  1 (0 NIL gist 0)
    2 (Reading is a lot of fun\. I enjoy spending some time on reading everyday\.) (100 :out)
  1 (0 you like reading 0)
    2 (0 book-genre 0)
      3 (0 science fiction 0)
        4 (I like reading science fiction\. I go check websites and find ones with the highest score\.) (100 :out)
      3 (0 health 0)
        4 (I like reading about 2 \. I go check websites and find ones with the highest score\.) (100 :out)
      3 (0 art 0)
        4 (I like reading about 2 \. I go check websites and find ones with the highest score\.) (100 :out)
      3 (0 religion 0)	
        4 (I like reading about 2 \. I go check websites and find ones with the highest score\.) (100 :out)
      3 (0 ethics 0)
        4 (I like reading about 2 \. I go check websites and find ones with the highest score\.) (100 :out)
      3 (I like reading 2 \. I go check websites and find ones with the highest score\.) (100 :out)
    2 (0 book club 0)
      3 (Being in a book club is fun\! It\'s also a good place to socialize\.) (100 :out)
    2 (0 library 0)
      3 (I like going to the library\. It\'s always fun to find a new book\.) (100 :out)
    2 (0 kindle 0)
      3 (That sounds nice\. I personally like kindle better\, but some people still prefer paper books\.) (100 :out)
    2 (0 audio books 0)
      3 (That\'s nice\. I like listening to audio books in the car\.) (100 :out)
    2 (Reading is a lot of fun\. I enjoy it too\.) (100 :out)
  1 (0 do not like reading 0)
    2 (That\'s fine\, there are plenty of other fun things to do\.) (100 :out)
  1 (0 NIL gist 0)
    2 (There\'s a lot of good books out there to discover\.) (100 :out)
))
