(defun make-timegraph () nil)
(defun assert-prop (prop tg) nil)
(defun eval-prop (prop tg) nil)
(defun encode-timestamp (nsec sec minute hour day month year &key timezone offset into) nil)
(defun update-lower-bound-inst (e1 ts &optional tg) nil)
(defun update-upper-bound-inst (e1 ts &optional tg) nil)